services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - JAVA_OPTS=-Xmx256m
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - graph-network

  # Optional: DynamoDB Admin GUI for easy management
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    networks:
      - graph-network

volumes:
  dynamodb-data:

networks:
  graph-network:
    driver: bridge